### ISSUE TITLE
Openhaptics SDK

### ISSUE THREAD

**Issue by antoniocl96** [fsuarez6/phantom_omni#3]
Hi, i am writing you because i am having troubles to find the Openhaptics SDK, i am trying to get registered and download it from the 3Dsystems forums but no confirmation email arrives, do you know any other webpage where i can find it?
Best regards
Antonio
Cc @jlblancoc

**Comment by fsuarez6** [comment]
Check the releases area of this repo. There is a zip file that should be useful for you: https://github.com/fsuarez6/phantom_omni/releases/download/0.2.0/OpenHapticsAE_Linux_v3_0.zip

**Comment by jlblancoc** [comment]
Thanks, @fsuarez6 , it was really useful!
