### ISSUE TITLE
can't locate node [omni] in package [omni_common]

### ISSUE THREAD

**Issue by robot0102** [fsuarez6/phantom_omni#4]
I used phantom_omni to do my work in Ubuntu 16.04 and Ubuntu 14.04 environments. When I roslaunch omni_common omni.launch, the system prompts: ERROR: cannot launch node of type [omni_common/omni]: can't locate node [omni] in package [omni_common].

**Comment by fsuarez6** [comment]
This is a generic ROS related _issue_. 
Please search in https://answers.ros.org/questions/ and you will see there are plenty of questions of the type:
```
cannot launch node of type [NODE_NAME]: can't locate node [NODE_NAME] in package [PACKAGE_NAME].
```

**Comment by robot0102** [comment]
Thank you. I've solved the problem

**Comment by AndyRay1998** [comment]
How did you solve it? Does it influence usage of this package? @a1625395374

**Comment by fsuarez6** [comment]
You need to source `~/catkin_ws/devel/setup.bash`. Check this thread for a decent explanation.
https://answers.ros.org/question/229365/do-i-really-need-to-source-catkin_wsdevelsetupbash/

**Comment by 10179013** [comment]
ubuntu20.04
I also meet the same error:
I have already source ~/catkin_ws/devel/setup.bash,but it can not work ,what should I do to fix it?
`smile@smile-Vostro-3400:~$ roslaunch omni_common omni.launch
... logging to /home/smile/.ros/log/f82bbf86-7ab8-11ed-aa33-cdf626ed73a4/roslaunch-smile-Vostro-3400-17902.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://smile-Vostro-3400:46861/

SUMMARY
========

PARAMETERS
 * /robot_description: <?xml version="1....
 * /rosdistro: noetic
 * /rosversion: 1.15.15

NODES
  /
    omni1 (omni_common/omni)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    rviz (rviz/rviz)

auto-starting new master
process[master]: started with pid [17911]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to f82bbf86-7ab8-11ed-aa33-cdf626ed73a4
process[rosout-1]: started with pid [17921]
started core service [/rosout]
process[robot_state_publisher-2]: started with pid [17924]
ERROR: cannot launch node of type [omni_common/omni]: Cannot locate node of type [omni] in package [omni_common]. Make sure file exists in package path and permission is set to executable (chmod +x)
process[rviz-4]: started with pid [17928]

`
