### ISSUE TITLE
libPhantomIOLib42.so not found

### ISSUE THREAD

**Issue by AndyRay1998** [fsuarez6/phantom_omni#6]
![图片](https://user-images.githubusercontent.com/35843385/78026912-ff0fd780-738e-11ea-9c2e-4796a1d26027.png)

As shown in the image, after I install everything according to http://fsuarez6.github.io/projects/geomagic-touch-in-ros/, I got this issue while trying to catkin_make my workspace.

I am using ROS kinetics and Ubuntu 16.04 x64.

Thank you very much!

**Comment by AndyRay1998** [comment]
The pic is not showing. The error appears like:

/usr/bin/ld: warning: libPhantomIOLib42.so, needed by /usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libHD.so, not found (try using -rpath or -rpath-link)
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libHD.so: undefined reference to `setPreServoCallback'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libHD.so: undefined reference to `get_stylus_presence'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libHD.so: undefined reference to `is_phantom_velocity_check_enabled'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libHD.so: undefined reference to `set_phantom_ramp_forces_rate'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libHD.so: undefined reference to `get_phantom_temp_normalized_6dof'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libHD.so: undefined reference to `get_gimbal_encoders'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libHD.so: undefined reference to `get_phantom_pos'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libHD.so: undefined reference to `CREATE_EVENT'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libHD.so: undefined reference to `command_motor_dac_values'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libHD.so: undefined reference to `get_phantom_nominal_max_torque_force'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libHD.so: undefined reference to `get_phantom_temp_normalized'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libHD.so: undefined reference to `enable_phantom_forces'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libHD.so: undefined reference to `send_phantom_force_6dof'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libHD.so: undefined reference to `InitializeCriticalSectionAndSpinCount'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libHD.so: undefined reference to `LeaveCriticalSection'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libHD.so: undefined reference to `is_phantom_forces_enabled'

**Comment by fsuarez6** [comment]
I was able to replicate your error.

Your are probably missing the `phantomdevicedrivers` package. The OpenHaptics SDK is composed by two packages, please install both of them:
- openhaptics-ae_3.0-2_amd64.deb
- phantomdevicedrivers_4.3-3_amd64.deb

After that, I had to modify the symbolic link `/usr/lib/libraw1394.so.8`:
```
sudo rm -f /usr/lib/libraw1394.so.8
sudo ln -s /usr/lib/x86_64-linux-gnu/libraw1394.so.11 /usr/lib/libraw1394.so.8
```

Finally, there were some warnings regarding `omni_msgs`, pull the latest commit from the `hydro-devel` branch to get the fix.

_Tested with OpenHaptics SDK 3.0 in Ubuntu 16.04, 64 bits._

**Comment by AndyRay1998** [comment]
Thank you very much! 
I have successfully catkin_make the workspace, which I think is a sign of successful installation. 
I have tried your commands again and again and somehow it just worked.
