### ISSUE TITLE
hi,Where is the robot_ state_ publisher Feature Pack? 

### ISSUE THREAD

**Issue by qwewr** [fsuarez6/phantom_omni#8]

**Comment by qwewr** [comment]
Sorry to trouble you. Where is the robot_ state_ publisher Feature Pack? Can I have it?

**Comment by QRayMoor** [comment]
Hi, there. I found this link is failed when I tried to install **Geomagic_Touch_ROS_Drivers** , do you know how to fix it?

> Download and Extract OpenHaptics and Haptic Device drivers

> Download drivers using instructions at: https://3dsystems.teamplatform.com/pages/102863?t=fptvcy2zbkcc

**Comment by fsuarez6** [comment]
> Hi, there. I found this link is failed when I tried to install **Geomagic_Touch_ROS_Drivers** , do you know how to fix it?
> 
> > Download and Extract OpenHaptics and Haptic Device drivers
> 
> > Download drivers using instructions at: https://3dsystems.teamplatform.com/pages/102863?t=fptvcy2zbkcc

This was already answer in #3
https://github.com/fsuarez6/phantom_omni/issues/3
